### ISSUE TITLE
[SR-16116] swift-corelibs-foundation does not compile on macOS

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-corelibs-foundation#3168]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-16116      |
   |Radar             | None         |
   |Original Reporter | @adam-fowler      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: e879b4f83c986bbc368313e8f7d2bba6

  </details>

**Issue Description:**

Both toolchain that comes with Xcode 13.3.1 and latest snapshot produce the following error

``` java
/Users/adamfowler/Developer/swift/swift-corelibs-foundation/Sources/Foundation/AttributedString/Conversion.swift:314:5: Cannot find '_forEachField' in scope
```

**Comment by Fidetro** [comment]
hey, I have same problem,I use Xcode 13.4 and swift 5.6.1.  
How did you solve this problem?

**Comment by adam-fowler** [comment]
> hey, I have same problem,I use Xcode 13.4 and swift 5.6.1.
> How did you solve this problem?

I can not remember offhand. I guess if you want to compile latest swift-corelibs-foundation you need to be compiling with latest swift.

**Comment by Fidetro** [comment]
I have the following configuration and it works:
Xcode Version: 13.4.1
Toolchain: Swift 5.6.2 Release 2022-06-02 (a)

thanks

**Comment by MaxDesiatov** [comment]
This is still reproducible with Xcode 14.

**Comment by parkera** [comment]
With swift-corelibs-foundation's new focus as a compatibility layer only, we've decided that it shouldn't build for macOS. [swift-foundation](http://github.com/apple/swift-foundation) does compile for macOS, and furthermore does so as a SPM project.
