### ISSUE TITLE
[SR-15172] Lossless double conversion with JSONDecoder

### ISSUE THREAD

**Issue by macdrevx** [apple/swift-corelibs-foundation#3358]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15172      |
   |Radar             | rdar://82884961         |
   |Original Reporter | @macdrevx      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 13.0 beta 5; also reproducible on Xcode 12.5.1 (12E507)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 5729415c881e6956ae9ae0435ca86e35

  </details>

**Issue Description:**

    let str = "0.027121761950711698"
    let dbl = Double(str)!
    dbl == Double(dbl.description) // true
    try! dbl.description == String(data: JSONEncoder().encode(dbl), encoding: .utf8)! // true
    try! dbl == JSONDecoder().decode(Double.self, from: JSONEncoder().encode(dbl)) // false

   
JSONDecoder decodes the double differently than Double.

 

I would expect it to decode to the same value.

**Comment by parkera** [comment]
This appears to work with the newer JSONEncoder/Decoder implementation in swift-foundation. See also #5001
