### ISSUE TITLE
[SR-5970] Import encodeEncodable/decodeDecodable from stdlib into SwiftFoundation

### ISSUE THREAD

**Issue by lhoward** [apple/swift-corelibs-foundation#3805]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5970      |
   |Radar             | None         |
   |Original Reporter | @lhoward      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Task        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3f7d007b909b3a5bd5b680f5e9bab4a2

  </details>

**Issue Description:**

Support for encoding/decoding Swift codable values inside Foundation archives. The code to do this is in stdlib, it just needs to be integrated.

**Comment by parkera** [comment]
I'm not sure if this one is still an issue. Please let us know if so.
