### ISSUE TITLE
[SR-5209] Searching a Data slice with default range results in a crash

### ISSUE THREAD

**Issue by CharlesJS** [apple/swift-corelibs-foundation#3845]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5209      |
   |Radar             | rdar://problem/36261057         |
   |Original Reporter | @CharlesJS      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f61c821c7374601c9542542c2b5e3bfb

  </details>

**Issue Description:**

When searching a Data object that is a slice of another Data object, the default value for the 'range' parameter becomes the bounds of the parent data, rather than the slice. This results in a crash when trying to search using range(of:&#41;, as you can see by running the code below:

``` java
import Foundation

let data = "FooBar".data(using: .ascii)!
let slice = data[3...] // Bar

let range = slice.range(of: "a".data(using: .ascii)!) // Crash! NSRangeException: range {0, 6} exceeds data length 3
```

**Comment by ahknight** [comment]
> +1, still occurs in Swift 4.0.3
> 
> ```java
> import Foundation
> let dataOne = Data(0..<100)
> let dataTwo = Data(25..<30)
> dataOne.range(of: dataTwo) // returns: .some(25..<30)
> dataOne.subdata(in: 10..<90).range(of: dataTwo) // returns: .some(15..<20)
> dataOne[10..<90].range(of: dataTwo) // CRASH!
> ```

This code longer seems to crash on Swift 5.8.  The result of the last line is `25...30`.
