### ISSUE TITLE
[SR-4964] Subscripting a subscripted Data offsets incorrectly

### ISSUE THREAD

**Issue by phausler** [apple/swift-corelibs-foundation#3854]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4964      |
   |Radar             | None         |
   |Original Reporter | @phausler      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 18a067db1c19adbef1965bcb6c9a59e2

  </details>

**relates to**:  
* [SR-5105](https://bugs.swift.org/browse/SR-5105) inconsistent index of Data  

**Issue Description:**

    import Foundation

    let d1 = Data(bytes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    let slice1 = d1[5..<10]
    assert(d1[5] == slice1[5])

**Comment by parkera** [comment]
Seems to work ok now.
