### ISSUE TITLE
[SR-4802] Data slicing regression

### ISSUE THREAD

**Issue by Bouke** [apple/swift-corelibs-foundation#3865]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4802      |
   |Radar             | rdar://problem/32134716         |
   |Original Reporter | @Bouke      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 3.1.1 Ubuntu 16.04

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug, 3.1Regression        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 8658f007c32a034ffc11f2738558eafd

  </details>

**Issue Description:**

``` java
let data = Data(bytes: [1, 2, 3, 4])
let slice = data[2..<4]
dump(slice)
dump(Data(slice))
dump(Array(slice))
```

The expected output would be the bytes \[3, 4\], however it returns respectively:

``` java
[1, 2]
[3, 4]
[random, random]
```

**Comment by parkera** [comment]
This looks resolved to me as well.
