### ISSUE TITLE
[SR-3888] gyb_foundation_support.py incorrectly implements _unconditionallyBridgeFromObjectiveC

### ISSUE THREAD

**Issue by phausler** [apple/swift-corelibs-foundation#3889]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3888      |
   |Radar             | rdar://problem/30400139         |
   |Original Reporter | @phausler      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug, BuildScript, SDKOverlay        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 91492ff8d5813205e107850de79d3814

  </details>

**Issue Description:**

\_unconditionallyBridgeFromObjectiveC should construct an empty structural types when the reference NSValue is nil.

gyb_foundation_support.py has the following line:  
let unwrappedSource = source!

which defeats the use of \_unconditionallyBridgeFromObjectiveC

**Comment by parkera** [comment]
This gyb file is gone now.
