### ISSUE TITLE
[SR-2895] Audit and resolve the Optional-as-Any warnings in Foundation

### ISSUE THREAD

**Issue by belkadan** [apple/swift-corelibs-foundation#3923]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2895      |
   |Radar             | None         |
   |Original Reporter | @belkadan      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 770b9f93f7f3d50495b3f19fbac47a8f

  </details>

**Issue Description:**

Both swift-corelibs-foundation and the Apple Foundation overlay (swift/stdlib/public/SDK/Foundation) have quite a few warnings for implicit conversion of Optional to Any; it is likely that at least some of these are true issues (particularly the ones in string interpolations). Every one of these warnings should be addressed in some way.

**Comment by parkera** [comment]
This is done, and #5000 also addresses all outstanding warnings.
