### ISSUE TITLE
[SR-2869] Can't use Date in NSPredicate

### ISSUE THREAD

**Issue by bjhomer** [apple/swift-corelibs-foundation#3925]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2869      |
   |Radar             | None         |
   |Original Reporter | @bjhomer      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 8.0 b2  
macOS Sierra 10.12  
Apple Swift version 3.0.1 (swiftlang-800.0.56 clang-800.0.42)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3db2af26dc72ef6e8288d176973521e2

  </details>

**Issue Description:**

The Swift 3 migrator maps most uses of `NSDate` to `Date`. When used with `NSPredicate`, this proves to be somewhat of a pain.

``` java
import Foundation

let date = Date()
let predicate = NSPredicate("date < %@", date)
// error: argument type 'Date' does not conform to expected type 'CVarArg'
```

The compiler suggests `NSPredicate("date < %@", date as CVarArg)` as a fix-it, which does indeed work, but seems awkward. `NSPredicate("date < %@", date as NSDate)` is more natural, but still makes `Date` a second-class citizen here.

Is there a better option?

**Comment by parkera** [comment]
The newer `Predicate` type should better support this kind of thing.
