### ISSUE TITLE
[SR-2744] Errors when running REPL on Ubuntu 16.04

### ISSUE THREAD

**Issue by Bouke** [apple/swift-corelibs-foundation#3931]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2744      |
   |Radar             | None         |
   |Original Reporter | @Bouke      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Ubuntu server 16.04, Swift 3.0.1 Preview 1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Foundation    |
   |Labels            | Bug, Linux        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9d11eb334a20f053d1c5a5b0c149517c

  </details>

**relates to**:  
* [SR-2743](https://bugs.swift.org/browse/SR-2743) Incomplete install instructions for Ubuntu  

**Issue Description:**

I installed Ubuntu server 16.04 with OpenSSH + default options. When running the following code, there's an error about missing symbols.

``` java
$ swift
Welcome to Swift version 3.0 (swift-3.0-RELEASE). Type :help for assistance.
  1> import Foundation
  2> NSURL(string: "http://swift.org")
error: Couldn't lookup symbols:
  type metadata accessor for Foundation.NSURL
  Foundation.NSURL.__allocating_init (string : Swift.String) -> Swift.Optional<Foundation.NSURL>
```

**Comment by parkera** [comment]
If this is still an issue, I think we'll need to reopen it back in the swift repository because it's about the install itself.
