### ISSUE TITLE
[SR-13837] Swift Decimal type crashes on a specific double value

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#3965]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13837      |
   |Radar             | rdar://problem/71197338         |
   |Original Reporter | mohsena (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 55011e39127ea36a3fecf9509d128bc7

  </details>

**Issue Description:**

(lldb) expr Decimal(1.9446744073709552E19)  
(Decimal) $R26 = 19446744073709551616.000000

(lldb) expr Decimal(**1.8446744073709552E19**)  
error: Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).  
The process has been returned to the state before expression evaluation.

(lldb) expr Decimal(2.8446744073709552E19)  
(Decimal) $R28 = 28446744073709551616.000000

The value above in bold crashes Swift **1.8446744073709552E19**

All other values are fine, even if I simply replace last 2E+19 with 0E+19

**Comment by FreaksOnE** [comment]
I'm still having this issue

Swift version 5.9.2 (swift-5.9.2-RELEASE)
Target: x86_64-unknown-linux-gnu

let x = Decimal(string: "0.000323730024699578384923825161654754178742")!
let y = Decimal(string: "0.000340281878241659205929686457001887171685")!
let result = x / y // crash
