### ISSUE TITLE
[SR-5070] NSJSONSerialization.JSONObjectWithData doesn't support Double

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4096]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5070      |
   |Radar             | None         |
   |Original Reporter | shawn.hampton (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

iOS 10.2, Xcode 8.2.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | mattrajca (JIRA)      |
   |Priority          | Medium      |

   

   md5: 8eb2fed3170eacedcfbc488ba9838c4c

  </details>

**Issue Description:**

Summary:  
DBL_MIN = 2.2250738585072014e-308. However using this value and values above this in JSON results in "\[0\] (null) "NSDebugDescription" : "Number wound up as NaN around character 256."". So it seems that NSJSONSerialization. JSONObjectWithData does not support Double.

Steps to Reproduce:  
Example JSON:

``` java
"{\n  \"nestedArray\" : [\n    \"{\\n  \\\"age\\\" : 25,\\n  \\\"name\\\" : \\\"Shawn\\\"\\n}\"\n  ],\n  \"testEnum\" : \"First\",\n  \"number\" : 9223372036854775807,\n  \"nestedModel\" : \"{\\n  \\\"age\\\" : null,\\n  \\\"name\\\" : \\\"Mohit\\\"\\n}\",\n  \"port\" : null,\n  \"useSsl\" : false,\n  \"double\" : 2.225073858507201e-308\n}"
```

Swift code :

``` java
        let jsonString = "{\n  \"nestedArray\" : [\n    \"{\\n  \\\"age\\\" : 25,\\n  \\\"name\\\" : \\\"Shawn\\\"\\n}\"\n  ],\n  \"testEnum\" : \"First\",\n  \"number\" : 9223372036854775807,\n  \"nestedModel\" : \"{\\n  \\\"age\\\" : null,\\n  \\\"name\\\" : \\\"Mohit\\\"\\n}\",\n  \"port\" : null,\n  \"useSsl\" : false,\n  \"double\" : 2.225073858507201e-308\n}"
        if let dataFromString = jsonString.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: true) {
            do {
                let object = try NSJSONSerialization.JSONObjectWithData(dataFromString, options: .AllowFragments)
            } catch {
                NSLog("\(error)")
            }
        }
```

Expected Results:  
Get object with double = 2.2250738585072014e-308.

Observed Results:  
catching error : "\[0\] (null) "NSDebugDescription" : "Number wound up as NaN around character 256.""

Version:  
iOS 10.2/ xcode 8.2.1

**Comment by parkera** [comment]
This appears to work now.
