### ISSUE TITLE
[SR-1777] URL.absoluteURL / URL.absoluteString incorrectly became optional in 2.3 / 3.0?

### ISSUE THREAD

**Issue by pcantrell** [apple/swift-corelibs-foundation#4139]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1777      |
   |Radar             | None         |
   |Original Reporter | @pcantrell      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7c5e4ae1632051eaa6513556ca19699c

  </details>

**Issue Description:**

In Swift 2.3 / 3.0, URL’s absoluteURL and absoluteString properties are now optional. (They were non-optional on NSURL in Swift 2.2-.)

I can’t figure out why they should be. In every test case I can think of, either the URL initializer fails with nil, or it succeeds and the URL’s absolute\* properties are not nil. I’ve tried:

-   empty string

-   URLs without a protocol

-   syntactically invalid URLs

-   URL containing dubious characters ("\0")

-   URLs constructed with strings containing unpaired Unicode surrogate chars

The docs don’t explain anything about when those properties could return nil.

I’m wondering if this is a mistake in the mapping from Obj-C?

**Comment by parkera** [comment]
This old bug appears to be fixed or no longer relevant.
