### ISSUE TITLE
[SR-1608] NSStream, NSInputStream and NSOutputStream need implementations

### ISSUE THREAD

**Issue by phausler** [apple/swift-corelibs-foundation#4148]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1608      |
   |Radar             | None         |
   |Original Reporter | @phausler      |
   |Type              | Bug    |
   |Status            | In Progress        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3488657a0f28ddf9753d7b1d2c73ef44

  </details>

**Issue Description:**

These classes are missing most of their implementations and can be backed by CFStream. Ideally they should follow the same pattern as other bridged (is-a) types like NSData or NSString however they could probably be implemented with a has-a implementation with little effort.

**Comment by parkera** [comment]
These are implemented.
