### ISSUE TITLE
[SR-1246] Inconsistent naming and declaration of String & NSString derivative properties and functions

### ISSUE THREAD

**Issue by groue** [apple/swift-corelibs-foundation#4159]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1246      |
   |Radar             | None         |
   |Original Reporter | @groue      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation, Standard Library    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1453e0d6656d71f2d9f021adea95860f

  </details>

**Issue Description:**

Hello,

In the latest swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain (master), there are inconsistencies in the following declarations:

``` java
extension String {
    public func lowercased() -> String
    public func uppercased() -> String
}

extension NSString {
    public var uppercased: String { get }
    public var lowercased: String { get }
    public var capitalized: String { get }
    public var localizedUppercase: String { get }
    public var localizedLowercase: String { get }
    public var localizedCapitalized: String { get }
}
```

We see that we have sometimes properties, sometimes functions, and they sometimes end in -ed, and sometimes not.

**Comment by parkera** [comment]
We resolved these differences as much as we could. Future enhancements will happen to the `String` type instead of `NSString`.
