### ISSUE TITLE
[SR-1162] Allow building Foundation on OS X from build-script without headers in /usr/include/

### ISSUE THREAD

**Issue by belkadan** [apple/swift-corelibs-foundation#4160]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1162      |
   |Radar             | None         |
   |Original Reporter | @belkadan      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c6b3ad65ea8a582c10c122ba857615b2

  </details>

**Issue Description:**

Currently, using build-script on OS X to build Foundation (swift-corelibs-foundation) will fail if the system doesn't have the Command Line Tools package installed, i.e. if they do not have any headers in /usr/include/. There's actually a `--sysroot` option to Foundation's 'configure' script, but (a) build-script doesn't pass it, and (b) the script doesn't fully respect it on OS X. (It might be something as simple as the use of `--sysroot` instead of `-isysroot` as an argument to Clang.)

**Comment by parkera** [comment]
swift-corelibs-foundation no longer builds for macOS in any case.
