### ISSUE TITLE
[SR-741] importing Foundation should import CoreFoundation

### ISSUE THREAD

**Issue by drewcrawford** [apple/swift-corelibs-foundation#4165]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-741      |
   |Radar             | None         |
   |Original Reporter | @drewcrawford      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Linux x64  
swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug, Linux        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: d47746f40cfa9f93d3fec8d971ee14b1

  </details>

**Issue Description:**

This is very similar to SR-567.

``` java
import Foundation
CFSwapInt16BigToHost(2)
```

Expected results: Works (like on Darwin)

Actual results: `error: use of unresolved identifier 'CFSwapInt16BigToHost'` because CoreFoundation was not imported along with Foundation.

**Comment by parkera** [comment]
CF is still considered an implementation detail of Foundation on non-Darwin platforms.
