### ISSUE TITLE
[SR-465] configure script should generate main.swift for the test target

### ISSUE THREAD

**Issue by phausler** [apple/swift-corelibs-foundation#4173]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-465      |
   |Radar             | None         |
   |Original Reporter | @phausler      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 489f1f1ad4927e296d7c128c31b4ea78

  </details>

**Issue Description:**

this would avoid the missing Test constructor in the tests.

**Comment by parkera** [comment]
This old bug appears to be fixed or no longer relevant.
