### ISSUE TITLE
[SR-21] Standardize NSURL / NSPathUtilities behavior

### ISSUE THREAD

**Issue by jtbandes** [apple/swift-corelibs-foundation#4208]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-21      |
   |Radar             | rdar://problem/22424272         |
   |Original Reporter | @jtbandes      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Improvement        |
   |Assignee          | @parkera      |
   |Priority          | Medium      |

   

   md5: bcd1290e284ffe9fda05487cde2ea447

  </details>

**Issue Description:**

The methods provided in NSPathUtilities / NSURLPathUtilities categories adhere mostly to RFC 1808.

NSURLComponents, on the other hand, uses the more-modern RFC 3986 behavior.

My view is that continuing to expose RFC 1808–style behavior is harmful to users. Results may be unexpected:

``` java
NSURL(string: "http://one/two;three/four")!.URLByAppendingPathComponent("five")
// This returns "http://one/two/five;three/four".

// Paths whose last component starts/ends with a dot (.) also have problems:
let url = NSURL(fileURLWithPath: "/path/to/.file")

// Expected: ???
// Actual: ""
let ext = url.pathExtension!

// Expected (based on pathExtension being ""): "/path/to/.file"
// Actual: "/path/to/"
url.URLByDeletingPathExtension!

// Expected: same as original URL
// Actual: "/path/to./"
url.URLByDeletingPathExtension!.URLByAppendingPathExtension(ext)

// <rdar://18421068>, only recently resolved in El Capitan, was a similar issue in NSURLComponents.
```

This has produced some problems in Apple system behavior (see \<rdar://23241861\>), let alone latent bugs in third-party code.

These sorts of things should be hard to get wrong, rather than easy. I think the Foundation APIs could use some love here.

**Comment by parkera** [comment]
This is done - URL and URLComponents now use the same parser under the hood.

**Comment by jtbandes** [comment]
Done already? And it's not even 10 years old! 😄   Thanks 🙌
