### ISSUE TITLE
[SR-3658] Can't build CoreFoundation on Ubuntu 16.04, January 16

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4297]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3658      |
   |Radar             | None         |
   |Original Reporter | ewconnell (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Ubuntu 16.04

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 5         |
   |Component/s       | Compiler, Foundation    |
   |Labels            | Bug, Linux        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 39b731dec7a0058949a21269d2dc8b64

  </details>

**relates to**:  
* [SR-3648](https://bugs.swift.org/browse/SR-3648) Unable to Import Foundation  

**Issue Description:**

I tried updating my Ubuntu 16.04 build to use the January 16, 2017 snapshot. Jan 15 failed the same way. Swift build can't seem to find Block.h, which appears to be in the tree. If I specify that directory explicitly so it can find it, then it can't find the C++ \<vector\> header.

So something is definitely broken. My project builds fine with the Dec 13 release.

This is the output that is repeated over and over  
-------------------------------------------------

``` java
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/ed/swift/usr/lib/swift/CoreFoundation/CoreFoundation.h:56:10: note: in file included from /home/ed/swift/usr/lib/swift/CoreFoundation/CoreFoundation.h:56:
#include <CoreFoundation/CFBase.h>
         ^
/home/ed/swift/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/ed/swift/usr/lib/swift/CoreFoundation/CoreFoundation.h:56:10: note: in file included from /home/ed/swift/usr/lib/swift/CoreFoundation/CoreFoundation.h:56:
#include <CoreFoundation/CFBase.h>
         ^
/home/ed/swift/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>

etc....
```

Any ideas??

**Comment by parkera** [comment]
This older issue seems to be fixed or no longer relevant.
