### ISSUE TITLE
[SR-3516] NSDataDetector Missing in Foundation

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4305]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3516      |
   |Radar             | None         |
   |Original Reporter | aamctustwo (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Foundation    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: e32a1c3dd4d08633fbbbdc2c6f42a5a3

  </details>

**Issue Description:**

\`NSDataDetector\` currently does not exist in \`swift-corelibs-foundation\`.

From Apple's API reference: <https://developer.apple.com/reference/foundation/nsdatadetector>

**Comment by parkera** [comment]
We don't intend to port this functionality to swift-corelibs-foundation.
