### ISSUE TITLE
[SR-2391] No fixit for NSBundle.urlForResource(_, withExtension)

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4340]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2391      |
   |Radar             | None         |
   |Original Reporter | hexdreamer (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 4bce37ebf791377f69b26288b119034c

  </details>

**Issue Description:**

After conversion, this line of code:

guard let url = Bundle(for: type(of: self)).urlForResource("hexdreams", withExtension: "momd") else {

Has the error

/Users/kenny/Projects/PepperDogFetch/Submodules/hexdreamsCocoa/Tests/Model/HXTestDataController.swift:13:25: Value of type 'Bundle' has no member 'urlForResource'

The correct version should be:  
guard let url = NSBundle(for: type(of: self)).url(forResource:"hexdreams", withExtension: "momd") else {

BTW, the new type(of:) syntax makes this look really ugly now.

**Comment by parkera** [comment]
I don't think we're adding any more compatibility fix-its at this point, if it isn't already there.
