### ISSUE TITLE
[SR-2342] Support standalone builds of a full CoreFoundation.framework

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4341]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2342      |
   |Radar             | None         |
   |Original Reporter | copumpkin (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | New Feature, BuildScript        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 64fb215d00bd420034547cca8a6c30c9

  </details>

**Issue Description:**

~~I was very pleased to see <https://github.com/apple/swift-corelibs-foundation/commit/87d1a97d6af07fec568765c47daddff0aaa0d59c>, which allowed us to build CoreFoundation independently of Foundation, but that build still only builds a static library. A naive switch of `StaticLibrary` to `Framework` leads to weird ninja dependency errors (I can't find an example using the `Framework` product), and switching it for `DynamicLibrary` produces a ton of linker errors (mostly because it doesn't link ICU or libxml2, and doesn't inject all the `__UNICODE` symbols into the result object).~~

~~Highlighting~~ @phausler ~~as the author of the commit in question.~~

Edit: the above is all currently fixed, and `DynamicLibrary` is now the default. This issue is about trying to switch `DynamicLibrary` to `Framework`.

Motivation: the Nix package manager aims to be a (nearly) fully deterministic build system (with a strong preference for builds from source), and as part of that we build a full Mac toolchain from scratch (no Xcode or command-line tools). To do that, we use a wide range of Apple's open-source releases on opensource.apple.com. Unfortunately, Apple only releases a reduced version of CoreFoundation on there, and although it works for most of our use cases, the slight discrepancies between CF (-lite) and the proper CoreFoundation cause us some subtle issues. The CoreFoundation included in the swift Foundation project appears to be more complete and better suited to our use case.

**Comment by parkera** [comment]
We've long since switched to cmake for all of our builds.
