### ISSUE TITLE
[SR-1412] Cannot compile Foundation on ARM

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4353]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1412      |
   |Radar             | None         |
   |Original Reporter | rlovelett (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961358-187d8838-0521-4bdd-b8c2-0a6deb0e365c.gz)

      
<details>
  <summary>Environment</summary>

OS: Ubuntu 16.04 xenial  
Kernel: armv7l Linux 4.4.0-1009-raspi2  
CPU: ARMv7 rev 5 (v7l) @ 900MHz

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Foundation    |
   |Labels            | Bug, arm, armv7        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2400e3dbf340591e3f5a4c7b90f5bf16

  </details>

**Issue Description:**

While compiling CFString on ARM (Raspberry Pi 2) I am running into a perplexing issue. It appears that the `va_list` typedef is being defined multiple times.

``` java
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/ryan/Source/swift-corelibs-foundation/../build/Ninja-ReleaseAssert/foundation-linux-armv7/Foundation/usr/lib/swift/CoreFoundation/CoreFoundation.h:58:10: note: in file included from /home/ryan/Source/swift-corelibs-foundation/../build/Ninja-ReleaseAssert/foundation-linux-armv7/Foundation/usr/lib/swift/CoreFoundation/CoreFoundation.h:58:
#include <CoreFoundation/CFCalendar.h>
         ^
/home/ryan/Source/swift-corelibs-foundation/../build/Ninja-ReleaseAssert/foundation-linux-armv7/Foundation/usr/lib/swift/CoreFoundation/CFCalendar.h:21:10: note: in file included from /home/ryan/Source/swift-corelibs-foundation/../build/Ninja-ReleaseAssert/foundation-linux-armv7/Foundation/usr/lib/swift/CoreFoundation/CFCalendar.h:21:
#include <CoreFoundation/CFTimeZone.h>
         ^
/home/ryan/Source/swift-corelibs-foundation/../build/Ninja-ReleaseAssert/foundation-linux-armv7/Foundation/usr/lib/swift/CoreFoundation/CFTimeZone.h:23:10: note: in file included from /home/ryan/Source/swift-corelibs-foundation/../build/Ninja-ReleaseAssert/foundation-linux-armv7/Foundation/usr/lib/swift/CoreFoundation/CFTimeZone.h:23:
#include <CoreFoundation/CFString.h>
         ^
/home/ryan/Source/swift-corelibs-foundation/../build/Ninja-ReleaseAssert/foundation-linux-armv7/Foundation/usr/lib/swift/CoreFoundation/CFString.h:265:123: error: reference to 'va_list' is ambiguous
CFStringRef CFStringCreateWithFormatAndArguments(CFAllocatorRef alloc, CFDictionaryRef formatOptions, CFStringRef format, va_list arguments) CF_FORMAT_FUNCTION(3,0);
                                                                                                                          ^
/home/ryan/Source/build/Ninja-ReleaseAssert/swift-linux-armv7/lib/swift/clang/include/stdarg.h:30:27: note: candidate found by name lookup is 'va_list'
typedef __builtin_va_list va_list;
                          ^
/usr/include/stdio.h:79:20: note: candidate found by name lookup is 'va_list'
typedef _G_va_list va_list;
```

It would seem that `va_list` is being defined by multiple things in the include path.

**Comment by parkera** [comment]
This old bug appears to be fixed or no longer relevant.
