### ISSUE TITLE
[SR-1282] Add conversion String -> Bool

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4356]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1282      |
   |Radar             | None         |
   |Original Reporter | sdavids (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation, Standard Library    |
   |Labels            | New Feature, LanguageFeatureRequest        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 86692dd3cbe368d50f6ddd85e61d06bb

  </details>

**Issue Description:**

Please add a conversion from String to Bool.

``` java
init?(_ text: String)
```

The conversion method should be case insensitive.

Examples:

``` java
Bool("true") -> true
Bool("false") -> false
Bool("TrUE") -> true
Bool(" true ") -> nil
Bool("1") -> nil
Bool("Y") -> nil
Bool("whatever") -> nil 
```

This would be useful for JSON/XML processing.

**Comment by parkera** [comment]
Closing as noted above.
