### ISSUE TITLE
[SR-1232] Compiler crash when subscripting AnyObject

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4359]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1232      |
   |Radar             | None         |
   |Original Reporter | elia (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961312-223b3882-775d-4481-8e75-8e74169f516d.gz)

      
<details>
  <summary>Environment</summary>

    $ swift --version
    Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
    Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, Foundation    |
   |Labels            | Bug, 2.2Regression, CompilerCrash, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: a04034ca6465acfe74dad5b73274016d

  </details>

**Issue Description:**

The following piece of code causes a Segmentation Fault when compiled. This didn't happen in Swift 2.1 and earlier.

``` java
// The crash only happens when Foundation is available, possibly because of a subscript operator
// that it defines.
import Foundation

// This is a NSDictionary in my code, but it seems it doesn't matter to reproduce the crash.
let a: AnyObject = NSObject()

// Subscripting an AnyObject crashes the compiler, when b is declared as String, Int and possibly other types.
let b: String = a["c"]
```

    $ swiftc SR-###.swift 
    0  swift                    0x0000000111c1a4eb llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 43
    1  swift                    0x0000000111c197d6 llvm::sys::RunSignalHandlers() + 70
    2  swift                    0x0000000111c1ab4f SignalHandler(int) + 287
    3  libsystem_platform.dylib 0x00007fff8394f52a _sigtramp + 26
    4  libsystem_platform.dylib 0xffffffffffffffff _sigtramp + 2087389935
    5  swift                    0x000000011011e3a3 swift::TypeBase::getMemberSubstitutions(swift::DeclContext*) + 435
    6  swift                    0x000000011011e68c swift::TypeBase::getTypeOfMember(swift::ModuleDecl*, swift::Type, swift::DeclContext*) + 60
    7  swift                    0x000000010ff586b7 (anonymous namespace)::CalleeCandidateInfo::CalleeCandidateInfo(swift::Type, llvm::ArrayRef<swift::constraints::OverloadChoice>, unsigned int, bool, swift::constraints::ConstraintSystem*) + 647
    8  swift                    0x000000010ff531f9 swift::ASTVisitor<(anonymous namespace)::FailureDiagnosis, bool, void, void, void, void, void>::visit(swift::Expr*) + 9369
    9  swift                    0x000000010ff4ca42 swift::constraints::ConstraintSystem::diagnoseFailureForExpr(swift::Expr*) + 82
    10 swift                    0x000000010ff50941 swift::constraints::ConstraintSystem::salvage(llvm::SmallVectorImpl<swift::constraints::Solution>&, swift::Expr*) + 4113
    11 swift                    0x000000010ffb71a0 swift::TypeChecker::solveForExpression(swift::Expr*&, swift::DeclContext*, swift::Type, swift::FreeTypeVariableBinding, swift::ExprTypeCheckListener*, swift::constraints::ConstraintSystem&, llvm::SmallVectorImpl<swift::constraints::Solution>&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 736
    12 swift                    0x000000010ffbc93d swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::Type, swift::ContextualTypePurpose, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::ExprTypeCheckListener*) + 525
    13 swift                    0x000000010ffbdb84 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*) + 100
    14 swift                    0x000000010ffbdd29 swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int) + 281
    15 swift                    0x000000010ffd312c (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 556
    16 swift                    0x000000010ffd2ee1 swift::TypeChecker::typeCheckDecl(swift::Decl*, bool) + 161
    17 swift                    0x000000011000f82d swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 381
    18 swift                    0x000000011000f4bc swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) + 140
    19 swift                    0x000000010ffa66a9 swift::performTypeChecking(swift::SourceFile&, swift::TopLevelContext&, swift::OptionSet<swift::TypeCheckingFlags, unsigned int>, unsigned int) + 1609
    20 swift                    0x000000010fe289ca swift::CompilerInstance::performSema() + 4090
    21 swift                    0x000000010f96c326 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 934
    22 swift                    0x000000010f96b41d frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2781
    23 swift                    0x000000010f966e3c main + 1932
    24 libdyld.dylib            0x00007fff8cd895ad start + 1
    Stack dump:
    0.  Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file SR-###.swift -target x86_64-apple-macosx10.9 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -color-diagnostics -module-name main -o /var/folders/1_/cz0w0jms4fl0bqrrj65nxlqw0000gn/T/SR-###-4a350e.o 
    1.  While type-checking declaration 0x7ff79a887878 at SR-###.swift:9:1
    2.  While type-checking expression at [SR-###.swift:9:17 - line:9:22] RangeText="a["c"]"
    <unknown>:0: error: unable to execute command: Segmentation fault: 11
    <unknown>:0: error: compile command failed due to signal (use -v to see invocation)

**Comment by parkera** [comment]
This old bug appears to be fixed or no longer relevant.
