### ISSUE TITLE
[SR-283] swift3 build fails with foundation

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4372]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-283      |
   |Radar             | None         |
   |Original Reporter | iPad_dude (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 36170006e764316791c65bfde0a23cbb

  </details>

**Issue Description:**

the documentation states that foundation can be built

but with this  
build-script --release --foundation --build-subdir=osx

it doesn't

Foundation/NSObject.swift:11:8: error: could not build Objective-C module 'CoreFoundation'  
import CoreFoundation  
^  
\[162/253\] CompileC: CoreFoundation/String.subproj/CFString.c  
ninja: build stopped: subcommand failed.  
./build-script: command terminated with a non-zero exit status 1, aborting

without foundation, build is ok

**Comment by parkera** [comment]
This old bug appears to be fixed.
