### ISSUE TITLE
[SR-3298] Initializing TimeZone with Identifier results in wrong type/kind.

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4437]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3298      |
   |Radar             | None         |
   |Original Reporter | aaroncrespo (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 3.0.1 Xcode Version 8.2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug, SDKOverlay        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b1c50b35a172a505428c7f4d999bdc1a

  </details>

**Issue Description:**

Initializing a TimeZone by identifier with an identifier matching the user's current timezone results in an unexpected TimeZone kind.

input:

``` java
// hardware set to America/New_York
var timezone = TimeZone.current
var atimezone = TimeZone.autoupdatingCurrent
var ftimezone = TimeZone(identifier: "America/New_York")!
dump(timezone)
dump(atimezone)
dump(ftimezone)
```

output:

``` java
▿ America/New_York (current)
  - identifier: "America/New_York"
  - kind: "current"
  ▿ abbreviation: Optional("EST")
    - some: "EST"
  - secondsFromGMT: -18000
  - isDaylightSavingTime: false
▿ America/New_York (autoupdatingCurrent)
  - identifier: "America/New_York"
  - kind: "autoupdatingCurrent"
  ▿ abbreviation: Optional("EST")
    - some: "EST"
  - secondsFromGMT: -18000
  - isDaylightSavingTime: false
▿ America/New_York (current)
  - identifier: "America/New_York"
  - kind: "*current*"
  ▿ abbreviation: Optional("EST")
    - some: "EST"
  - secondsFromGMT: -18000
  - isDaylightSavingTime: false
```

expected output:

``` java
▿ America/New_York (current)
  - identifier: "America/New_York"
  - kind: "current"
  ▿ abbreviation: Optional("EST")
    - some: "EST"
  - secondsFromGMT: -18000
  - isDaylightSavingTime: false
▿ America/New_York (autoupdatingCurrent)
  - identifier: "America/New_York"
  - kind: "autoupdatingCurrent"
  ▿ abbreviation: Optional("EST")
    - some: "EST"
  - secondsFromGMT: -18000
  - isDaylightSavingTime: false
▿ America/New_York (current)
  - identifier: "America/New_York"
  - kind: "*fixed*"
  ▿ abbreviation: Optional("EST")
    - some: "EST"
  - secondsFromGMT: -18000
  - isDaylightSavingTime: false
```

**Comment by parkera** [comment]
I think this issue is now fixed.
