### ISSUE TITLE
[SR-3261] memory not freed after call deallocate on UnsafeMutablePointer

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4439]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3261      |
   |Radar             | None         |
   |Original Reporter | xray (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift 3  
xcode 8.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug, Leak        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0efef760cf6c02546b8e6f8f83d55510

  </details>

**Issue Description:**

Both Xcode memory report and instruments can't detect memory freed by deallocate, instruments also report memory leak. here's simple code to reproduce

``` java
struct Test {
    
    var ptrToInt: UnsafeMutablePointer<Int>
    
    init() {
        ptrToInt = UnsafeMutablePointer<Int>.allocate(capacity: 1)
        ptrToInt.initialize(to: 42)
    }
    
    func deleteValue() {
        ptrToInt.deinitialize(count: 1)
        ptrToInt.deallocate(capacity: 1)
    }
}

var x = [Test]()
var i = 0;
while(i < 1000000) {
    i = i + 1
    x.append(Test())
}
while(i > 0) {
    i = i - 1
    x.popLast()?.deleteValue()
}
```

the memory never goes down when it finished. and instruments gives a lots memory leak.

**Comment by parkera** [comment]
It seems this was not reproducible. In any case it should not have been transferred from swiftlang/swift. If it is still an issue, please open a new bug there. Thanks.
