### ISSUE TITLE
[SR-2671] Date Components return value instead of nil

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4443]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2671      |
   |Radar             | None         |
   |Original Reporter | erica (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961602-2b962402-ed32-452d-87a4-4da55f5eea62.gz)

      
<details>
  <summary>Environment</summary>

Xcode 8

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0cfc50f542146fceb8eeb2f9d4156906

  </details>

**Issue Description:**

let dc = DateComponents(hour: 5, minute: 2)  
print(dc.value(for: .second))

/// The calendar and timeZone and isLeapMonth property values cannot be retrieved by this method.  
public func value(for component: Calendar.Component) -\> Int?

Returns: Optional(9223372036854775807) instead of nil

p.s. the whole "isLeapMonth" thing for EVERY DATE COMPONENTS is really annoying

**Comment by parkera** [comment]
This is now fixed.
