### ISSUE TITLE
[SR-2640] Swift Json parsing

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4444]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2640      |
   |Radar             | None         |
   |Original Reporter | trololo (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f32192d30795588e086b648c79fb1472

  </details>

**Issue Description:**

For this JSON

...  
{"population": 1200, "lat": "-100.52353", "lng": "96.424532", "name": "name"},  
...

this code works very strange.

if let city = cities\[ndx\] as? \[String: AnyObject\],  
let population: UInt64 = (city\["population"\] as? NSNumber)!.unsignedLongLongValue {  
if (population \> 0) {

if let name = city\["name"\] as? String,  
let lat: Double = Double((city\["lat"\] as? String)!),  
let lon: Double = Double((city\["lng"\] as? String)!),  
}  
}

That is,  
to retrieve integer value I have to use AnyObject \> NSNumber \> UInt64 conversion but for double value: AnyObject \> String \> Double.  
Imho, this is a bad practise. Languages like Java or ObjC provides better expirience to work with JSON data.

Question on stackoverflow:

<http://stackoverflow.com/questions/39497728/swift-json-parsing-unpredictable-behaviour>

**Comment by parkera** [comment]
I don't think there is anything additional for Foundation to do here.
