### ISSUE TITLE
[SR-4656] Data subscript outside bounds should not return 0

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4528]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4656      |
   |Radar             | None         |
   |Original Reporter | Thommü (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift Version 3.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 4dd4b70f5e6cf15e82ac8ee2500b7b8b

  </details>

**Issue Description:**

When subscripting outside bounds there is no error but the result is 0

let a = "A".data(using: .utf8)!  
print(a\[0\]) // 65  
print(a\[123\]) // 0

**Comment by parkera** [comment]
This seems to behave as expected now.
