### ISSUE TITLE
[SR-1799] CoreFoundation has not be audited for nullability

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4569]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1799      |
   |Radar             | None         |
   |Original Reporter | KaiDANTE (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 053a9800719c46ba7394b265d7da6be2

  </details>

**Issue Description:**

After speaking to an Apple engineer during WWDC 2016 in the Swift Open Hour, he mentioned that it seems like CoreFoundation has not yet been audited for nullability. Specifically, the example that lead to the discovery is as follows:

``` java
let someMutableCFData = CFDataCreateMutable(nil, 0)!
```

CFDataCreateMutable() returns CFMutableData!, which lead him to think nullability hasn't been handled or audited.

**Comment by parkera** [comment]
We don't intend to update CF for nullability.
