### ISSUE TITLE
[SR-1565] UnsafeMutablePointer calling C function is empty occasionally.

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#4574]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1565      |
   |Radar             | None         |
   |Original Reporter | GregoryW (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961388-0033b32f-8074-4dec-a85b-af16c63cd4bd.gz)

      
<details>
  <summary>Environment</summary>

Ubuntu 15.10  
Swift 2016-05-09 Snapshot

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation, Standard Library    |
   |Labels            | Bug, Runtime        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9e8e0bbe9743e223d01e27fac8dadd60

  </details>

**Issue Description:**

Converting a Swift String to a C String and calling a C function has a chance to be the empty string, about 20% from what I've observed visually.

I have the following code snippet in my .swift file:

``` none
print(query)
```

Outputs: INSERT INTO DB2_TEST_TABLE (TEXT) VALUES ('KdhtXMmr18n2L9K88eMlGn7CcctT9RwKSB1FebW397VI5uG1yhc3uavuaOb9vyJcXyHZzsRwpC5iUzahEcaYatja7kaqGHss6YhteYQr')

------------------------------------------------------------------------

``` none
print(String(cString: UnsafeMutablePointer<Int8>(query.cString(using: NSUTF8StringEncoding))!))
```

Outputs: INSERT INTO DB2_TEST_TABLE (TEXT) VALUES ('KdhtXMmr18n2L9K88eMlGn7CcctT9RwKSB1FebW397VI5uG1yhc3uavuaOb9vyJcXyHZzsRwpC5iUzahEcaYatja7kaqGHss6YhteYQr')

------------------------------------------------------------------------

``` none
table_fetch(self.conn, UnsafeMutablePointer<Int8>(query.cString(using: NSUTF8StringEncoding)))
```

(table_fetch is a linked C function)

------------------------------------------------------------------------

In table_fetch (.c file), the first few lines are the following:

``` none
TABLE_RESULT * table_fetch (ODBC *odbc, char *queryStr) {

    FILE* fp;
    fp = fopen("/home/gregory/result.txt", "a+");
    fprintf(fp, "String: %s\n", queryStr);
    fprintf(fp, "Length: %d\n", strlen(queryStr));
    fclose(fp);
```

The output from that is  
String:  
Length: 0

queryStr is "" (empty) not NULL.

Nothing else is happening in between, it seems like this is a Swift issue, I can't think of any other reason why this is happening.

**Comment by parkera** [comment]
I don't think there is anything really for us to do with this bug at this point.
