### ISSUE TITLE
`DateInterval`’s `contains(_:)` method doesn’t work

### ISSUE THREAD

**Issue by Gerzer** [apple/swift-corelibs-foundation#4588]
On Darwin, the following code prints `true`:
```swift
import Foundation
let formatter = ISO8601DateFormatter()
let end = formatter.date(from: "2022-05-16T04:00:00Z")!
let middle = formatter.date(from: "2022-05-10T04:00:00Z")!
let interval = DateInterval(start: .distantPast, end: end)
print(interval.contains(middle)) // Should print `true`, which indeed it does on Darwin but which it doesn’t on Linux.
```
On Linux, the exact same code unexpectedly prints `false`. I suspect that this is an issue with this repository’s implementation of `contains(_:)`.

**Comment by YOCKOW** [comment]
https://github.com/apple/swift-corelibs-foundation/blob/bfead15ba7a547a8e2ea79dfd8be97de1153245d/Sources/Foundation/DateInterval.swift#L143-L151

I guess `abs` is the culprit.

**Comment by Gerzer** [comment]
> https://github.com/apple/swift-corelibs-foundation/blob/bfead15ba7a547a8e2ea79dfd8be97de1153245d/Sources/Foundation/DateInterval.swift#L143-L151
> 
> I guess `abs` is the culprit.

I agree; that was my first thought when I looked at the code. I suspect that `distantPast`’s `timeIntervalSinceReferenceDate` is negative, which is a scenario that the current implementation doesn’t handle properly. Just taking the values’ respective additive inverses instead of their absolute values is probably sufficient to fix the issue.
