### ISSUE TITLE
Where does swift-corelibs-foundation fetch TLS root certificates from on Windows?

### ISSUE THREAD

**Issue by chriskilding** [apple/swift-corelibs-foundation#4625]
When Foundation APIs (e.g. URLSession) are used on Apple platforms, TLS root certificates are fetched from the Keychain.

When these APIs are used on Windows (through swift-corelibs-foundation), what trust store are TLS root certificates fetched from? (Additionally, could you point me to the code that handles this?)

**Comment by lxbndr** [comment]
URLSession is backed by curl, which is built with native Windows [Schannel](https://docs.microsoft.com/en-us/windows/win32/secauthn/secure-channel) support. It uses system certificate store.

**Comment by chriskilding** [comment]
Great, thanks for confirming that.

Is the Schannel backend selected by default in the swift-corelibs-foundation Windows build? (A cursory search for the Curl 'with-schannel' flag in the repository didn't return any results, so I can't tell where this is being effectively set.)

**Comment by chriskilding** [comment]
Alternatively, is it an assumption in the build process that the user will supply a Curl on the build path, that has been compiled with Schannel support? (And therefore it's up to the user, or CI environment, to actually do this?)

**Comment by lxbndr** [comment]
I believe [this is the repo](https://github.com/compnerd/swift-build) used to produce official snapshots. At the moment it is powered by [Azure Pipelines](https://compnerd.visualstudio.com/swift-build/_build). Yeah, CURL build options are in the pipeline: https://github.com/compnerd/swift-build/blob/8476f27405c45d932a31ba16bdf3e86f90e43b2a/.ci/vs2022.yml#L604

**Comment by chriskilding** [comment]
Thanks. Before I close this issue, are there any other open source implementations of Swift APIs which use TLS? (For example, are there OSS implementations of Network.framework, or Secure Transport, or Security.framework?)

**Comment by lxbndr** [comment]
I am not aware of any project of this exact kind. What comes closest to mind is [SwiftNIO](https://github.com/apple/swift-nio). But it is not a part of standard Swift API.
