### ISSUE TITLE
`Date.FormatStyle` and `DateStyle` and `TimeStyle` not implemented

### ISSUE THREAD

**Issue by 0xTim** [apple/swift-corelibs-foundation#4646]
Yet more missing APIs - https://developer.apple.com/documentation/foundation/date/formatstyle/timestyle and https://developer.apple.com/documentation/foundation/date/formatstyle/datestyle

**Comment by parkera** [comment]
These are all (with one exception for DateComponentsFormatter) done in swift-foundation. See also #5001
