### ISSUE TITLE
JSONDecoder accepts invalid JSON

### ISSUE THREAD

**Issue by dhoepfl** [apple/swift-corelibs-foundation#4682]
This should fail to decode:

```swift
import Foundation

let t = #"{ "key":"Te\\\\nst", }"#
print(t)

let decoder = JSONDecoder()

struct Test : Decodable {
   let key: String
}

let b = try decoder.decode(Test.self, from: t.data(using: .utf8)!)
print(b)
print(b.key)
```

JSON does not allow the extra “,” at the end of an object. ([See specification](https://www.json.org/img/object.png))

Adding another “,” correctly fails with “No string key for value in object around line 1, column 20.”.

**Comment by dhoepfl** [comment]
I just learned about `allowsJSON5` which should default to `false`. Setting it to `false` manually does not fix it.

**Comment by parkera** [comment]
Many JSON parsers, including Foundation's, allow for trailing commas as a convenience even though it is not allowed via the spec.
