### ISSUE TITLE
`JSONEncoder` floating point behavior differs between Darwin and non-Darwin implementation

### ISSUE THREAD

**Issue by fumoboy007** [apple/swift-corelibs-foundation#4704]
The floating point behavior of [`JSONEncoder`](https://developer.apple.com/documentation/foundation/jsonencoder) differs between the Darwin and non-Darwin implementation of Foundation.

## Test Case

```swift
import Foundation

let array = [
  1.1
]

let jsonEncoder = JSONEncoder()

let jsonBytes = try! jsonEncoder.encode(array)
let jsonString = String(decoding: jsonBytes, as: UTF8.self)

print(jsonString)
```

## Darwin Output

```
[1.1000000000000001]
```

## Non-Darwin Output

```
[1.1]
```

**Comment by fumoboy007** [comment]
If I had a vote, I would vote for the non-Darwin behavior, which is neater.

One could argue the Darwin behavior is more precise but I think that argument misses the fact that floating point is imprecise to begin with… one cannot tell whether the floating point value actually represents `1.1` or `1.1000000000000001`.

So, in the absence of precision, I would suggest choosing the neater one.

**Comment by fumoboy007** [comment]
[This](https://github.com/apple/swift/commit/a32dacb131bc8cc44fc3ae88c2a90f91bd8fe10c) Swift commit changed Swift’s floating point formatting logic, mentioning the following:
> This format is also ideal for logging, debugging, and other general display. In particular, the shortness guarantee avoids the confusion of unnecessary additional digits, so that the result of `1.0 / 10.0` consistently displays as `0.1` instead of `0.100000000000000000001`.

**Comment by fumoboy007** [comment]
Filed [FB11996256](http://feedbackassistant.apple.com/feedback/11996256) requesting that the Darwin implementation be updated to match the non-Darwin implementation.

**Comment by 21DCS059** [comment]
i want to contribute in this project please assign it to me.

**Comment by fumoboy007** [comment]
@21DCS059 See above comment. There shouldn’t be any action needed in this repository. Instead, I filed [FB11996256](http://feedbackassistant.apple.com/feedback/11996256), which requests that Apple modify their closed-source version of Foundation.

**Comment by parkera** [comment]
This produces `[1.1]` using swift-foundation's `JSONEncoder`. See also #5001.
