### ISSUE TITLE
iOS 17 Data equality checks have changed [JSONEncoding/JSONDecoding]

### ISSUE THREAD

**Issue by samitaha2** [apple/swift-corelibs-foundation#4812]
Data equality checks have incorrectly changed on iOS 17.

Step to reproduce:

Run XCTestCase file in iOS 16. It will pass.
Run XCTestCase file in iOS 17. It will fail.

Suspected Cause:

In iOS 17, Data has changed how it performs equality. Previously equality did not care about ordered keys, now it does.
I've noticed if I modify the test case to use a JSONEncoder setting of encoder.outputFormatting = .sortedKeys, then it passes.

Reason this is a bug:

This is unexpected and changed behavior. Equality should not care what the ordering of the keys are when comparing one data object to another data object. Ordering is irrelevant for a JSON object. It's the content that matters. This will cause a huge regression for us in our previously released app if this hits production.

```
import XCTest

final class JSONDecodingTest: XCTestCase {
    
    struct Address: Codable {
        let street: String
        let city: String
        let state: String
        let postalCode: String
    }

    struct OrderItem: Codable {
        let productID: String
        let productName: String
        let quantity: Int
    }

    struct Order: Codable {
        let orderID: String
        let totalAmount: Double
        let items: [OrderItem]
    }

    struct User: Codable {
        let id: Int
        let username: String
        let email: String
        let address: Address
        let orders: [Order]
    }

    struct RootObject: Codable {
        let user: User
    }

    
    func testData() throws {
        
        let object1Json: String = """
        {
          "user": {
            "id": 12345,
            "username": "johndoe",
            "email": "john.doe@example.com",
            "address": {
              "street": "456 Elm St",
              "city": "Somewhere",
              "state": "NY",
              "postalCode": "54321"
            },
            "orders": [
              {
                "orderID": "A987",
                "totalAmount": 75.99,
                "items": [
                  {
                    "productID": "P123",
                    "productName": "Widget",
                    "quantity": 2
                  },
                  {
                    "productID": "P456",
                    "productName": "Gizmo",
                    "quantity": 1
                  }
                ]
              },
              {
                "orderID": "B543",
                "totalAmount": 32.50,
                "items": [
                  {
                    "productID": "P789",
                    "productName": "Thingamajig",
                    "quantity": 3
                  }
                ]
              }
            ]
          }
        }

        """
        let encoder = JSONEncoder()
        encoder.outputFormatting = .sortedKeys
        
        let itemData = object1Json.data(using: .utf8)!
        let item = try JSONDecoder().decode(RootObject.self, from: itemData)
        
        let data1 = try encoder.encode(item)
        let data2 = try encoder.encode(item)
        
        
        XCTAssertTrue(data1 == data2)
    }
}
```

**Comment by samitaha2** [comment]
@ypli-chn FYI -- since I see in a recent commit you modified decoding for generics.

**Comment by ypli-chn** [comment]
@samitaha2  This library is just an open source version of Foundation, and only affects the behavior under Linux. The Foundation used in the iOS system is not from this repository.

**Comment by parkera** [comment]
The iOS 17 version is here: https://github.com/apple/swift-foundation/blob/main/Sources/FoundationEssentials/JSON/JSONDecoder.swift

**Comment by parkera** [comment]
>  Equality should not care what the ordering of the keys are when comparing one data object to another data object.

`Data` knows nothing about the JSON that created it. Using `sortedKeys` is indeed the correct way to make sure that the output of `JSONEncoder` remains stable.
