### ISSUE TITLE
Need to Import CoreFoundation next to Foundation

### ISSUE THREAD

**Issue by abegehr** [apple/swift-corelibs-foundation#4865]
Is it anticipated that I need to import CoreFoundation explicitly next to Foundation to use the symbols `CFBooleanGetTypeID` and `CFGetTypeID` when building for Linux?

I ran into the issue when adding json-apple dependency to my Vapor app. It ran as expected on macOS but when building for linux failed with:

```log
…
7.335 [13/884] Compiling JSON Dictionary+JSON.swift
7.335 /build/.build/checkouts/json-apple/Sources/JSON/Dictionary+JSON.swift:73:9: error: cannot find 'CFBooleanGetTypeID' in scope
7.335         CFBooleanGetTypeID() == CFGetTypeID(self)
7.335         ^~~~~~~~~~~~~~~~~~
7.335 /build/.build/checkouts/json-apple/Sources/JSON/Dictionary+JSON.swift:73:33: error: cannot find 'CFGetTypeID' in scope
7.335         CFBooleanGetTypeID() == CFGetTypeID(self)
7.335                                 ^~~~~~~~~~~
7.335 /build/.build/checkouts/json-apple/Sources/JSON/JSON.swift:644:9: error: cannot find 'CFBooleanGetTypeID' in scope
7.335         CFBooleanGetTypeID() == CFGetTypeID(self)
7.335         ^~~~~~~~~~~~~~~~~~
7.335 /build/.build/checkouts/json-apple/Sources/JSON/JSON.swift:644:33: error: cannot find 'CFGetTypeID' in scope
7.335         CFBooleanGetTypeID() == CFGetTypeID(self)
7.335                                 ^~~~~~~~~~~
7.356 error: fatalError
```
(more details here: https://github.com/shareup/json-apple/issues/6)

I created a simple repro here: https://github.com/abegehr/json-apple-vapor/
It turns out that when building on Linux and referencing `CFBooleanGetTypeID` or `CFGetTypeID`, CoreFoundation needs to be [imported](https://github.com/abegehr/json-apple-vapor/commit/7716bee7b6ec167a9dc09469cc11c6fb038586be) in every file that tries to reference these symbols, otherwise it fails with "cannot find in scope", even though Foundation is imported which in turn imports CoreFoundation. Building for macOS works as expected and I don't need to explicitly import CoreFoundation in each file.

I'm using Swift 5.9 and the default Dockerfile from vapor 4.89.0: https://github.com/abegehr/json-apple-vapor/blob/main/Dockerfile
Build command: `RUN swift build -c release --static-swift-stdlib -Xlinker -ljemalloc` - without the flags same error.

**Comment by compnerd** [comment]
Yes, `CoreFoundation` is an internal implementation detail, and is not really meant to be used outside of the implementation of Foundation itself.
