### ISSUE TITLE
Components features missing from Locale

### ISSUE THREAD

**Issue by MCJack123** [apple/swift-corelibs-foundation#4887]
## Description
The [`Locale.Components`](https://developer.apple.com/documentation/foundation/locale/components) struct (introduced in iOS 16/macOS 13), and its associated methods and constructors in `Locale`, are not implemented in this version of Foundation. This makes it impossible to use locales with different components on non-Apple targets.

## Expected behavior
The `Locale` struct is up-to-date with the current macOS/iOS Foundation library, including `Locale.Components`.

## Actual behavior
`Locale.Components` is missing, preventing compilation of code that uses it.

## Environment
- Arch Linux (latest)
- Swift 5.9.2 (Red Hat UBI9)
- Whichever `swift-corelibs-foundation` ships with Swift 5.9.2

**Comment by parkera** [comment]
Will be resolved by #5001
