### ISSUE TITLE
`URL.appendingPathComponent` incorrectly URL-encodes `:`

### ISSUE THREAD

**Issue by QuietMisdreavus** [apple/swift-corelibs-foundation#5028]
[Our tests have started failing in Swift-DocC](https://ci.swift.org/job/pr-swift-docc-linux/1456/) due to an update to the URL type that URL-encodes paths in more places. After some discussion offline, it seems like `URL.appendingPathComponent(_:)` is incorrectly encoding characters that only need to be encoded in the first path component of a URL.

cc @jrflat @parkera

**Comment by parkera** [comment]
Closing as completed (@jrflat )
