### ISSUE TITLE
`TimeZone` rounds second-offset unlike DarwinFoundation.

### ISSUE THREAD

**Issue by YOCKOW** [apple/swift-corelibs-foundation#5079]
The code below says all.

```swift

import Foundation

print(TimeZone(secondsFromGMT: 15)!.secondsFromGMT())
// Prints "15" with DarwinFoundation
// Prints  "0" with swift-corelibs-foundation

print(TimeZone(secondsFromGMT: 3690)!.secondsFromGMT())
// Prints "3690" with DarwinFoundation
// Prints "3720" with swift-corelibs-foundation

```

**Environment**
Swift version 6.0-dev (LLVM 57177aa1b91540b, Swift 8be62863326595c)
Target: x86_64-unknown-linux-gnu

**Comment by parkera** [comment]
On the macOS 15 Beta (which shares the same TimeZone implementation as Swift 6.0), I see these results:

```
  1> import Foundation
  2> print(TimeZone(secondsFromGMT: 15)!.secondsFromGMT())
15
  3> print(TimeZone(secondsFromGMT: 3690)!.secondsFromGMT())
3690
```

On the Ubuntu Swift 6 nightly snapshot from 8/22 I see these results:

```
  1> import Foundation
  2> print(TimeZone(secondsFromGMT: 15)!.secondsFromGMT())
15
  3> print(TimeZone(secondsFromGMT: 3690)!.secondsFromGMT())
3690
```

**Comment by parkera** [comment]
`swift-6.0-DEVELOPMENT-SNAPSHOT-2024-08-22-a`

**Comment by parkera** [comment]
So in other words, I can't reproduce the swift-corelibs-foundation result above. Is that from a previous release of Swift?

**Comment by YOCKOW** [comment]
> Is that from a previous release of Swift?

I’m sorry, but Swift which produced that result seems a little old. I confirmed that `FoundationEssentials` doesn’t have such a bug. I mean it is probably corelibs-foundation specific.

**Comment by parkera** [comment]
The test case above is using swift-corelibs-foundation (which re-exports FoundationEssentials' TimeZone type as of 6.0).

**Comment by YOCKOW** [comment]
Hmm🤔
There may be some other factors affecting this issue.
I'm going to try more investigation.

**Comment by YOCKOW** [comment]
| Toolchain                                      | This issue      |
|------------------------------------------------|-----------------|
| 5.10.1                                         | 🪰 exists      |
| `swift-5.10-DEVELOPMENT-SNAPSHOT-2024-05-31-a` | 🪰 exists      |
| `swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-19-a`  | 🪰 exists      |
| `swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-21-a`  | ✅ no problem  |
| `swift-DEVELOPMENT-SNAPSHOT-2024-07-15-a`      | 🪰 exists      |
| `swift-DEVELOPMENT-SNAPSHOT-2024-07-22-a`      | ✅ no problem  |

I wonder what happened around 20th July.
